[package]
name = "winapi_gui"
version = "1.0.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["winuser", "winbase", "handleapi", "processthreadsapi", "synchapi"] }
once_cell = "1.8.0"