[package]
name = "editify"
description = "A Stable Editor"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "editify"
path = "src/main.rs"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "*"
cocoa = "*"


[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = "0.52.0"
